spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=mdatec32

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true